[package]
name = "marccx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grass = "0.11.2"
rocket = "0.5.0-rc.2"
ssr_rs = "0.2.3"
